name: கிளி சோதனைகள்
on:
  push:
    branches:
      - மத்திய
  pull_request:
    branches:
      - மத்திய

jobs:
  test-ipa-nodejs:
    name: கணினியில் சோதனைகள்
    runs-on: ubuntu-latest
    steps:
      
      - name: Ouvrir la branche
        uses: actions/checkout@v3

      - name: Installer pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Préparation de Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Installer
        run: pnpm install

      - name: Installer playwright
        run: npx playwright install

      - name: Vérifier les tests
        run: pnpm சோதனை:node

      - name: Envoyer couverure à Codecov
        uses: codecov/codecov-action@v2
  
  test-ipa-navig:
    name: உலாவியில் சோதனைகள்
    runs-on: ubuntu-latest
    steps:
      
      - name: Ouvrir la branche
        uses: actions/checkout@v3

      - name: Installer pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Préparation de Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Installer
        run: pnpm install

      - name: Installer playwright
        run: npx playwright install

      - name: Vérifier les tests
        run: pnpm உலாவியில்:உலாவி

      - name: Envoyer couverure à Codecov
        uses: codecov/codecov-action@v2

  test-ipa-electron-principal:
    name: எதிர்மின்னி-மத்தியமானதில் சோதனைகள்
    runs-on: ubuntu-latest
    needs: test-ipa-nodejs
    steps:
      
      - name: Ouvrir la branche
        uses: actions/checkout@v3

      - name: Installer pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Préparation de Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Installer
        run: pnpm install

      - name: Installer playwright
        run: npx playwright install

      - name: Vérifier les tests
        run: pnpm சோதனை:électron-principal

      - name: Envoyer couverure à Codecov
        uses: codecov/codecov-action@v2
